//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higgs.Mbale.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderGrades = new HashSet<OrderGrade>();
            this.OrderGradeSizes = new HashSet<OrderGradeSize>();
        }
    
        public long OrderId { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public long StatusId { get; set; }
        public string CustomerId { get; set; }
        public long ProductId { get; set; }
        public long BranchId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    
        public virtual AspNetUser AspNetUsers { get; set; }
        public virtual AspNetUser AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUsers2 { get; set; }
        public virtual AspNetUser AspNetUsers3 { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<OrderGrade> OrderGrades { get; set; }
        public virtual ICollection<OrderGradeSize> OrderGradeSizes { get; set; }
    }
}
